summary: Packages and releases milpa and friends
description: |
  Creates a folder, by default `dist` with:

  - packages/milpa-$os-$arch.tgz: the packaged milpa executable, compa binary, for each supported arch
  - packages/compa-$os-$arch.shasum: the shasum binary for each supported arch
  - milpa.dev: html docs for commands, utils, and usage

  The packaged milpa kernel contains:

  - the `milpa` executable,
  - the `compa` binary,
  - milpa libraries,
  - readme, license, and changelog
arguments:
  - name: version
    description: The semver number to build
    required: true
    values:
      script: git tag -l
  - name: hostname
    description: the hostname where documentation and install scripts will be served under
    default: https://milpa.dev
  - name: targets
    description: the targets to build for
    variadic: true
    values:
      # remember to update .github/ISSUE_TEMPLATE/bug-report.yml
      static:
        - auto
        - linux/amd64
        - linux/arm64
        - linux/arm
        - linux/mips
        - darwin/amd64
        - darwin/arm64
options:
  output:
    description: the path where to put built assets in
    default: ""
  parallel:
    description: how many compilations to run at the same time
    default: "-1"
