linters-settings:
  gocyclo:
    min-complexity: 18

linters:
  fast: false
  enable:
    - deadcode
    - errcheck
    # - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
