version: "2"
linters:
  enable:
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - misspell
    - nakedret
    - nilerr
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unparam
    - whitespace
  settings:
    gocyclo:
      min-complexity: 18
    revive:
      rules:
        - name: dot-imports
          disabled: true
    tagliatelle:
      case:
        rules:
          yaml: kebab
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
