#!/usr/bin/env bash
# Copyright © 2021 Roberto Hidalgo <milpa@un.rob.mx>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# MILPA ROOT points to this installation of the milpa kernel
# lol, kernel. La gente bilingue seguro entiende el chiste.
export MILPA_ROOT=${MILPA_ROOT:-/usr/local/lib/milpa}
if [[ ! -d "$MILPA_ROOT" ]]; then
  >&2 echo "MILPA_ROOT is not a directory!: $MILPA_ROOT"
  exit 78
fi

# ignore some stuff if being called from within a command
if [[ "$MILPA_PATH_PARSED" == "" ]]; then
  # MILPA_PATH contains all known milpa repositories
  # Repositories are folders that contain a .milpa directory within and will look for comands
  # in the order directories appear there. Only run this loop on the parent
  # If MILPA_PATH is set, it'll start its search there
  _PATH="${MILPA_PATH//:/\/.milpa:}${MILPA_PATH:+/.milpa}"
  # then, we'll look at MILPA_ROOT/.milpa
  _PATH="${_PATH}${_PATH:+:}${MILPA_ROOT}/.milpa"
  # if the current working dir contains a .milpa folder, search that next
  _pwd="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
  [[ -d "$_pwd/.milpa" ]] && [[ ! "$_PATH" =~ :?$_pwd/.milpa:? ]] && _PATH="$_PATH:$_pwd/.milpa"
  # from there, it'll look for user repos at $XDG_DATA_HOME/milpa/repos
  # followed by global repos at ${MILPA_ROOT}/repos
  MILPA_REPOS_USER="${XDG_DATA_HOME:-$HOME/.local/share}/milpa/repos"
  MILPA_REPOS_GLOBAL="${MILPA_ROOT}/repos"
  MILPA_REPOS="$(find -L "$MILPA_REPOS_USER" "$MILPA_REPOS_GLOBAL" -maxdepth 1 -mindepth 1 -type d -print)"
  if [[ "$MILPA_REPOS" != "" ]]; then
    nb=$'\n'
    MILPA_PATH="$_PATH:${MILPA_REPOS//$nb/\/.milpa}"
  else
    MILPA_PATH="$_PATH"
  fi
  export MILPA_PATH_PARSED=1
fi
# bash is fine and all, but we need a little helper to run parsing for us
export MILPA_COMPA="${MILPA_COMPA:-$MILPA_ROOT/compa}"

export MILPA_PATH
# create an array from this MILPA_PATH
IFS=: read -ra MILPA_PATH_ARR <<<"$MILPA_PATH"

# bail early if we're autocompleting
[[ $1 == "__complete" ]] && exec "$MILPA_COMPA" "$@"



function @milpa.load_util () {
  # shell scripts can call load_milpa_util to load utils within the $MILPA_PATH
  # TODO: maybe bump $MILPA_COMMAND_REPO up in the path?
  local env_name
  for util_name in "$@"; do
    env_name="_MILPA_UTIL_${util_name//-/_}"
    if [[ "${!env_name}" == "1" ]]; then
      # util already loaded
      continue
    fi

    for pkg in ${MILPA_PATH_ARR[*]} ; do
      util_path="${pkg}/util/$util_name.sh"
      if [[ -f "$util_path" ]]; then
        set -o allexport
        # shellcheck disable=1090
        source "$util_path"
        set +o allexport
        export "${env_name?}=1"
        break
      fi
    done

    if [[ "${!env_name}" != "1" ]]; then
      # util not found
      >&2 echo "Missing util named $util_name"
      exit 78
    fi
  done
}

@milpa.load_util log
function @milpa.fail () {
  # print an error, then exit
  @milpa.log error "$*"
  exit 2
}

# create some files pipes for compa
compaOut=$(mktemp -t "compaOut.XXX")
compaErr=$(mktemp -t "compaErr.XXX")
trap 'rm -rf $compaOut $compaErr' ERR EXIT TERM

# figure out what the user is asking for
COMPA_OUT="$compaOut" "$MILPA_COMPA" "$@" 2>"$compaErr" || {
  exitCode=$?

  # provide answers to life, the universe and everything
  if [[ "$exitCode" == 42 ]]; then
    # render help
    less -FIRX < "$compaErr"
    rm -rf "$compaOut" "$compaErr"
    # compa exits with 42 when the user asked for help explicitly
    # but asking for help shouldn't be an error, so we exit cleanly
    exit
  fi

  # otherwise, something else happened
  cat "$compaOut"
  cat "$compaErr"
  rm -rf "$compaOut" "$compaErr"
  exit $exitCode
}

# load parsed arguments and MILPA_ environment variables
set -o allexport
eval "$(cat "$compaOut")" || @milpa.fail "Failed setting command environment"
set +o allexport
[[ -z "$MILPA_COMMAND_KIND" ]] && {
  @milpa.log info "lookup stderr: $(cat "$compaErr")"
  @milpa.log info "lookup stdout: $(cat "$compaOut")"
  @milpa.log info "milpa environment:"
  env | grep ^MILPA | sort | @milpa.log info
  @milpa.fail "Command lookup exited cleanly, but no command provided for execution"
}

# normalize verbose flag
[[ "${MILPA_VERBOSE:-$MILPA_OPT_VERBOSE}" == "true" ]] && export MILPA_VERBOSE="true"
# print debugging output if requested
[[ "$DEBUG" == 1 ]] && @milpa.log debug "lookup output: $(cat "$compaErr")"
@milpa.log debug "running <$MILPA_COMMAND_NAME from> <$MILPA_COMMAND_PATH> with arguments <${*}>"
@milpa.log debug "milpa environment:"$'\n'"$(env | grep ^MILPA | sort)"

# thanks compa, good bye
rm -rf "$compaOut" "$compaErr"

# Run hooks if available
if [[ -f "$MILPA_COMMAND_REPO/.milpa/hooks/before-run.sh" ]]; then
  set -o allexport
  # shellcheck disable=1091 source=/dev/null
  source "$MILPA_COMMAND_REPO/.milpa/hooks/before-run.sh"
  set +o allexport
fi

# Run the subcommand
case "$MILPA_COMMAND_KIND" in
  exec)
    exec "$MILPA_COMMAND_PATH" "$@" ;;
  source)
    # shellcheck disable=1090
    source "$MILPA_COMMAND_PATH";;
  *)
    @milpa.fail "Unable to continue running subcommand, unexpected kind <${MILPA_COMMAND_KIND}>."
esac
