name: Docs page not found
description: Tell us about a 404 you've found at https://milpa.dev
title: "[docs-404]: "
labels: [docs]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this 404 report!
  - type: input
    id: URL
    attributes:
      label: Not found URL
      description: Paste in the address you've found a 404 error at
      placeholder: ex. https://milpa.dev/not-found
    validations:
      required: true
  - type: input
    id: URL
    attributes:
      label: Referral URL
      description: Paste in the address where you found the link that took you to the 404 error
      placeholder: ex. https://milpa.dev/some/command
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Any additional details?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you saw!
    validations:
      required: false
