summary: Builds compa for dev or test
description: |
  By default, using a git-generated version
arguments:
  - name: version
    description: Sets a specific version
    default: auto
options:
  coverage:
    type: bool
    description: if provided, will output coverage reports
