#!/usr/bin/env bash
MILPA_PATH="$MILPA_ROOT${MILPA_PATH+:}$MILPA_PATH"
_pwd="$(pwd)"
[[ -d ".milpa" ]] && [[ ! "$MILPA_PATH" =~ :?$_pwd:? ]] && MILPA_PATH="$MILPA_PATH:$_pwd"
export MILPA_PATH
IFS=: read -ra MILPA_PATH_ARR <<<"$MILPA_PATH"
export MILPA_PATH_ARR

function load_milpa_util () {
  local env_name
  for util_name in "$@"; do
    env_name="_MILPA_UTIL_${util_name//-/_}"
    if [[ "${!env_name}" == "1" ]]; then
      # util already loaded
      continue
    fi

    for pkg in $MILPA_PATH_ARR ; do
      util_path="${pkg}/.milpa/util/$util_name.sh"
      if [[ -f "$util_path" ]]; then
        set -o allexport
        # shellcheck disable=1090
        source "$util_path"
        set +o allexport
        export "${env_name?}=1"
        continue
      fi
    done

    if [[ "${!env_name}" != "1" ]]; then
      # util not found
      >&2 echo "Missing util named $util_name"
    exit 2
    fi
  done
}

load_milpa_util log
function _fail () {
  _log error "$*"
  exit 2
}

if [[ "$#" -eq 0 ]]; then
  _log error "$("$MILPA_ROOT/src/milpa-helper" "$@")"
  exit 127
fi

newEnv="$("$MILPA_ROOT/src/milpa-helper" "$@")" || {
  exitCode=$?
  case "$exitCode" in
  42)
    # 42 help requested
    echo "$newEnv"
    exit
    ;;
  4*)
    # 40 bad arguments
    # 44 command not found
    _log error "$newEnv"
    exit $exitCode
  ;;
  *)
    exit $exitCode
  ;;
  esac
}

# load parsed arguments and MILPA_ environment variables
eval "$newEnv"

if [[ "${MILPA_VERBOSE}" == "1" ]]; then
  _log debug "running <$MILPA_COMMAND_NAME from> <$MILPA_COMMAND_PATH> with arguments <${*}>"
fi

if [[ -f "$MILPA_COMMAND_PACKAGE/.milpa/util/before-run.sh" ]]; then
  set -o allexport
  # shellcheck disable=1091
  source "$MILPA_COMMAND_PACKAGE/.milpa/util/before-run.sh"
  set +o allexport
fi

case "$MILPA_COMMAND_KIND" in
  exec) exec "$MILPA_COMMAND_PATH" "$@" ;;
  source)
    # shellcheck disable=1090
    source "$MILPA_COMMAND_PATH";;
  *) _log warning "Unsure how to run $MILPA_COMMAND_NAME. Found $MILPA_COMMAND_PATH, but it is neither a .sh file nor executable" && _fail "Unable to continue running sub-command."
esac
