on:
  push:
    branches:
      - '**'
      - '!gh-pages'
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.x

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.10.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.0.0
        with:
          skip-pkg-cache: true
          version: v1.54.2
          args: --timeout 3m --verbose

      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
          ignore_paths: test/_helpers/bats-assert test/_helpers/bats-file test/_helpers/bats-support

      - name: Build compa and environment
        run: |
          version="test-$(date -u "+%s")"
          echo "TEST_MILPA_VERSION=$version" >> $GITHUB_ENV
          echo "MILPA_ROOT=$(pwd)" >> $GITHUB_ENV
          echo "MILPA_PATH=$(pwd)/internal" >> $GITHUB_ENV
          echo "MILPA_UPDATE_CHECK_DISABLED=1" >> $GITHUB_ENV
          echo "BATS_LIB_PATH=$(pwd)/test/_helpers" >> $GITHUB_ENV
          go build -ldflags "-s -w -X main.version=${version}" -o compa -cover

      - name: Unit tests
        run: |
          go install gotest.tools/gotestsum@latest
          $(pwd)/milpa dev test unit --coverage

      - name: Integration tests
        run: |
          $(pwd)/milpa dev test integration --coverage

      - name: milpa doctor
        run: |
          export GOCOVERDIR=$(pwd)/test/coverage/doctor
          mkdir -p "$GOCOVERDIR"
          $(pwd)/milpa itself doctor
          $(pwd)/milpa dev test coverage-report


      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: test/coverage.cov
