on:
  push:
    tags:
      - "[1-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "[1-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "[1-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
      - "[1-9]+.[0-9]+.[0-9]+"
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x

      - name: Checkout source
        uses: actions/checkout@v1

      - name: Cache go modules
        uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-go-${{ env.cache-name }}-
            ${{ runner.OS }}-go-

      - name: Setup dependencies
        run: |
          curl -LO https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
          tar xf upx-3.96-amd64_linux.tar.xz
          sudo mv upx-3.96-amd64_linux /usr/local/bin/upx

      - name: create release
        id: build
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${GITHUB_REF##*/}"
          export MILPA_ROOT=$(pwd)
          $(pwd)/milpa release docs-image --docker-login "${GITHUB_REPOSITORY##*/}:GITHUB_TOKEN" "$version"

          prerelease = "false"
          if [[ "$GITHUB_REF" == *-* ]]; then
            prerelease="true"
            echo "Building a pre-release"
          fi
          echo "::set-output name=prerelease::$prerelease"
          $(pwd)/milpa release build "${version}"
          $(pwd)/milpa cl show "${version}" >> release-notes.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workflow }}/release-notes.txt
          files: |
            dist/packages/*.tgz
            dist/packages/*.shasum
          prerelease: ${{ steps.build.outputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: update github pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        # re-enable when we only wanna build for stable releases
        # if: ${{ steps.build.outputs.prerelease == "false" }}
        with:
          branch: gh-pages
          folder: dist/milpa.dev
