on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-go-${{ env.cache-name }}-
            ${{ runner.OS }}-go-

      - name: Setup dependencies
        run: |
          version="${GITHUB_REF##*/}"
          echo "version is $version"
          echo "::group::install upx"
          curl -LO https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
          tar xf upx-3.96-amd64_linux.tar.xz
          sudo mv upx-3.96-amd64_linux/upx /usr/local/bin/upx
          echo "::endgroup::"

          echo "::group::build compa"
          go build -ldflags "-s -w -X main.version=CI" -o compa
          echo "::endgroup::"

          echo "::group::Release notes"
          git config --global user.email "milpa+ci@un.rob.mx"
          git config --global user.name "Milpa CI"
          git ls-remote | awk '/refs\/notes/ {print $2}' | while read -r noteKind; do
            git pull --rebase origin "$noteKind"
          done

          mkdir -p dist
          git show "${version}" | awk '/^commit /{exit} f; /^Date: /{f=1}' > dist/release-notes.md
          cat dist/release-notes.md
          wc -c dist/release-notes.md
          echo "::endgroup::"

          go get -u github.com/mitchellh/gox

      - name: create release
        id: build
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${GITHUB_REF##*/}"
          export MILPA_ROOT=$(pwd)
          export MILPA_DISABLE_UPDATE_CHECKS="1"
          echo "::group::release docker image"
          $(pwd)/milpa release docs-image --docker-login "unrob:GITHUB_TOKEN" "$version"
          echo "::endgroup::"

          export PATH="$PATH:$(pwd)"
          prerelease="false"
          if [[ "$GITHUB_REF" == *-* ]]; then
            prerelease="true"
            echo "Building a pre-release"
          fi
          echo "::set-output name=prerelease::$prerelease"

          echo "::group::building release"
          $(pwd)/milpa release build "${version}"
          echo "::endgroup::"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: dist/release-notes.md
          files: |
            dist/*.tgz
            dist/*.shasum
          prerelease: ${{ steps.build.outputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: update github pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        # re-enable when we only wanna build for stable releases
        # if: ${{ steps.build.outputs.prerelease == "false" }}
        with:
          branch: gh-pages
          folder: dist/milpa.dev
